'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ProgramExecutionsSinceLastUpdateCheck() As Integer
            Get
                Return CType(Me("ProgramExecutionsSinceLastUpdateCheck"),Integer)
            End Get
            Set
                Me("ProgramExecutionsSinceLastUpdateCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CheckForUpdates() As Boolean
            Get
                Return CType(Me("CheckForUpdates"),Boolean)
            End Get
            Set
                Me("CheckForUpdates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property closeAfterCreatingRestorePoint() As Boolean
            Get
                Return CType(Me("closeAfterCreatingRestorePoint"),Boolean)
            End Get
            Set
                Me("closeAfterCreatingRestorePoint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property confirmRestorePointDeletions() As Boolean
            Get
                Return CType(Me("confirmRestorePointDeletions"),Boolean)
            End Get
            Set
                Me("confirmRestorePointDeletions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property firstRun() As Boolean
            Get
                Return CType(Me("firstRun"),Boolean)
            End Get
            Set
                Me("firstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("536, 603")>  _
        Public Property windowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("windowSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("windowSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("682, 221")>  _
        Public Property diskUsageWindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("diskUsageWindowSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("diskUsageWindowSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property dontBugTheUserAboutPuttingTheEXEFileSomewhereSafe() As Boolean
            Get
                Return CType(Me("dontBugTheUserAboutPuttingTheEXEFileSomewhereSafe"),Boolean)
            End Get
            Set
                Me("dontBugTheUserAboutPuttingTheEXEFileSomewhereSafe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("27")>  _
        Public Property column1Size() As Integer
            Get
                Return CType(Me("column1Size"),Integer)
            End Get
            Set
                Me("column1Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("191")>  _
        Public Property column2Size() As Integer
            Get
                Return CType(Me("column2Size"),Integer)
            End Get
            Set
                Me("column2Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("140")>  _
        Public Property column3Size() As Integer
            Get
                Return CType(Me("column3Size"),Integer)
            End Get
            Set
                Me("column3Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("125")>  _
        Public Property column4Size() As Integer
            Get
                Return CType(Me("column4Size"),Integer)
            End Get
            Set
                Me("column4Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property boolDontBugMeAboutMovingEXE() As Boolean
            Get
                Return CType(Me("boolDontBugMeAboutMovingEXE"),Boolean)
            End Get
            Set
                Me("boolDontBugMeAboutMovingEXE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property deleteOldRestorePoints2() As Boolean
            Get
                Return CType(Me("deleteOldRestorePoints2"),Boolean)
            End Get
            Set
                Me("deleteOldRestorePoints2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property maxDaysManualDelete() As Short
            Get
                Return CType(Me("maxDaysManualDelete"),Short)
            End Get
            Set
                Me("maxDaysManualDelete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property boolLogDeletedRestorePoints() As Boolean
            Get
                Return CType(Me("boolLogDeletedRestorePoints"),Boolean)
            End Get
            Set
                Me("boolLogDeletedRestorePoints") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SeaGreen")>  _
        Public Property barColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("barColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("barColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UpdateRequired() As Boolean
            Get
                Return CType(Me("UpdateRequired"),Boolean)
            End Get
            Set
                Me("UpdateRequired") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("743, 396")>  _
        Public Property logFileViewerWindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("logFileViewerWindowSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("logFileViewerWindowSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property debug() As Boolean
            Get
                Return CType(Me("debug"),Boolean)
            End Get
            Set
                Me("debug") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property customColors2() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("customColors2"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("customColors2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("stable")>  _
        Public Property updateChannel() As String
            Get
                Return CType(Me("updateChannel"),String)
            End Get
            Set
                Me("updateChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property lastUpdateTime() As Date
            Get
                Return CType(Me("lastUpdateTime"),Date)
            End Get
            Set
                Me("lastUpdateTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property checkForUpdatesEveryInDays() As Short
            Get
                Return CType(Me("checkForUpdatesEveryInDays"),Short)
            End Get
            Set
                Me("checkForUpdatesEveryInDays") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowMessageBoxAfterSuccessfulCreationOfRestorePoint() As Boolean
            Get
                Return CType(Me("ShowMessageBoxAfterSuccessfulCreationOfRestorePoint"),Boolean)
            End Get
            Set
                Me("ShowMessageBoxAfterSuccessfulCreationOfRestorePoint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowMessageBoxAfterSuccessfulDeletionOfRestorePoints() As Boolean
            Get
                Return CType(Me("ShowMessageBoxAfterSuccessfulDeletionOfRestorePoints"),Boolean)
            End Get
            Set
                Me("ShowMessageBoxAfterSuccessfulDeletionOfRestorePoints") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property checkSystemDrivesForFullShadowStorage() As Boolean
            Get
                Return CType(Me("checkSystemDrivesForFullShadowStorage"),Boolean)
            End Get
            Set
                Me("checkSystemDrivesForFullShadowStorage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bal")>  _
        Public Property notificationType() As String
            Get
                Return CType(Me("notificationType"),String)
            End Get
            Set
                Me("notificationType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property allowDeleteOfAllRestorePoints() As Boolean
            Get
                Return CType(Me("allowDeleteOfAllRestorePoints"),Boolean)
            End Get
            Set
                Me("allowDeleteOfAllRestorePoints") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("70")>  _
        Public Property eventLogColumn1Size() As Short
            Get
                Return CType(Me("eventLogColumn1Size"),Short)
            End Get
            Set
                Me("eventLogColumn1Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("130")>  _
        Public Property eventLogColumn2Size() As Short
            Get
                Return CType(Me("eventLogColumn2Size"),Short)
            End Get
            Set
                Me("eventLogColumn2Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property eventLogColumn3Size() As Short
            Get
                Return CType(Me("eventLogColumn3Size"),Short)
            End Get
            Set
                Me("eventLogColumn3Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("876, 371")>  _
        Public Property eventLogWindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("eventLogWindowSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("eventLogWindowSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("138")>  _
        Public Property eventLogColumn4Size() As Short
            Get
                Return CType(Me("eventLogColumn4Size"),Short)
            End Get
            Set
                Me("eventLogColumn4Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("418")>  _
        Public Property eventLogSplitDistance() As Short
            Get
                Return CType(Me("eventLogSplitDistance"),Short)
            End Get
            Set
                Me("eventLogSplitDistance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property useSSL() As Boolean
            Get
                Return CType(Me("useSSL"),Boolean)
            End Get
            Set
                Me("useSSL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowFullDisksAsRed() As Boolean
            Get
                Return CType(Me("ShowFullDisksAsRed"),Boolean)
            End Get
            Set
                Me("ShowFullDisksAsRed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property useHTTPProxy() As Boolean
            Get
                Return CType(Me("useHTTPProxy"),Boolean)
            End Get
            Set
                Me("useHTTPProxy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property useSystemProxyConfig() As Boolean
            Get
                Return CType(Me("useSystemProxyConfig"),Boolean)
            End Get
            Set
                Me("useSystemProxyConfig") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property proxyAddress() As String
            Get
                Return CType(Me("proxyAddress"),String)
            End Get
            Set
                Me("proxyAddress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property proxyPort() As Integer
            Get
                Return CType(Me("proxyPort"),Integer)
            End Get
            Set
                Me("proxyPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property proxyUser() As String
            Get
                Return CType(Me("proxyUser"),String)
            End Get
            Set
                Me("proxyUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property proxyPass() As String
            Get
                Return CType(Me("proxyPass"),String)
            End Get
            Set
                Me("proxyPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property askToUpgrade() As Boolean
            Get
                Return CType(Me("askToUpgrade"),Boolean)
            End Get
            Set
                Me("askToUpgrade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property boolAskMeToSubmitIfViewingAnExceptionEntry() As Boolean
            Get
                Return CType(Me("boolAskMeToSubmitIfViewingAnExceptionEntry"),Boolean)
            End Get
            Set
                Me("boolAskMeToSubmitIfViewingAnExceptionEntry") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("788, 334")>  _
        Public Property updateMessageDialogSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("updateMessageDialogSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("updateMessageDialogSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property showPartialBetaChangeLogs() As Boolean
            Get
                Return CType(Me("showPartialBetaChangeLogs"),Boolean)
            End Get
            Set
                Me("showPartialBetaChangeLogs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("71")>  _
        Public Property column5Size() As Integer
            Get
                Return CType(Me("column5Size"),Integer)
            End Get
            Set
                Me("column5Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property restorePointListColumnOrder() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("restorePointListColumnOrder"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("restorePointListColumnOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property roundRestorePointAgeNumber() As Short
            Get
                Return CType(Me("roundRestorePointAgeNumber"),Short)
            End Get
            Set
                Me("roundRestorePointAgeNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sortingColumn() As Short
            Get
                Return CType(Me("sortingColumn"),Short)
            End Get
            Set
                Me("sortingColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property sortingOrder() As Short
            Get
                Return CType(Me("sortingOrder"),Short)
            End Get
            Set
                Me("sortingOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property eventLogSortingColumn() As Short
            Get
                Return CType(Me("eventLogSortingColumn"),Short)
            End Get
            Set
                Me("eventLogSortingColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property eventLogSortingOrder() As Short
            Get
                Return CType(Me("eventLogSortingOrder"),Short)
            End Get
            Set
                Me("eventLogSortingOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property mainWindowPosition() As Global.System.Drawing.Point
            Get
                Return CType(Me("mainWindowPosition"),Global.System.Drawing.Point)
            End Get
            Set
                Me("mainWindowPosition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property onlyGiveMeRCs() As Boolean
            Get
                Return CType(Me("onlyGiveMeRCs"),Boolean)
            End Get
            Set
                Me("onlyGiveMeRCs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property askBeforeCreatingRestorePoint() As Boolean
            Get
                Return CType(Me("askBeforeCreatingRestorePoint"),Boolean)
            End Get
            Set
                Me("askBeforeCreatingRestorePoint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property mountVolumeShadowCopyWindowPosition() As Global.System.Drawing.Point
            Get
                Return CType(Me("mountVolumeShadowCopyWindowPosition"),Global.System.Drawing.Point)
            End Get
            Set
                Me("mountVolumeShadowCopyWindowPosition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property DeleteOldSystemRestorePointsWindowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DeleteOldSystemRestorePointsWindowLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DeleteOldSystemRestorePointsWindowLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property DiskSpaceUsageWindowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DiskSpaceUsageWindowLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DiskSpaceUsageWindowLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ManageSystemRestoreStorageSpaceWindowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("ManageSystemRestoreStorageSpaceWindowLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ManageSystemRestoreStorageSpaceWindowLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property TaskSchedulerWindowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("TaskSchedulerWindowLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("TaskSchedulerWindowLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property eventLogFormWindowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("eventLogFormWindowLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("eventLogFormWindowLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property boolFirstRun() As Boolean
            Get
                Return CType(Me("boolFirstRun"),Boolean)
            End Get
            Set
                Me("boolFirstRun") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Restore_Point_Creator.My.MySettings
            Get
                Return Global.Restore_Point_Creator.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
